<?php
/**
 * Created by PhpStorm.
 * User: Babatunde Adelabu
 * Date: 9/11/18
 * Time: 9:12 AM
 */

namespace App\Models;


use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use App\Helpers\Helper;

class Projects extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'projects';
    protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = ['name', 'type', 'image', 'description', 'url', 'user_id'];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($obj) {
            Storage::disk('public')->delete($obj->image);
        });
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function user()
    {
        return $this->belongsTo('App\Models\Bio');
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */

    public function setImageAttribute($value)
    {
        // set attribute's name
        $attributeName = 'image';

        $this->attributes[$attributeName] = Helper::localImageUpload($this->attributes, $attributeName, 'public', '/images/projects', $value, true, 1200, 1600);

        // cloudinary image upload
        //$this->attributes[$attributeName] = Helper::cloudinaryImageUpload('/images/projects', $value, ['width'=> 1600, 'height' => 1200, 'crop'=> 'fit', 'format' => 'jpg']);
    }

}
